[package]
name = "wasm"
version = "0.1.0"
authors = ["Birb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

walrus = "0.18.0"
jvm = { path = "../jvm" }
rust-crypto = "0.2.36"
byteorder = "1.4.2"