[package]
name = "jvm-test"
version = "0.1.0"
authors = ["Birb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

jvm = { path = "../jvm" }
wasm = { path = "../wasm" }
wasmtime = "0.26.0"
clap = "2.33.3"
byteorder = "1.4.2"